### PR TITLE
Prepare for release of version 2.3

### PR DESCRIPTION
**Pull request by SBI-**
# Description
This is release 2.3 of the jazz development environment. Many incubating features are now deemed stable, and have also been documented in the [Wiki](https://github.com/jazz-community/jazz-debug-environment/wiki).

# Summary
- Upgrading is safe, all previous stable features have only received bug fixes where necessary
- To be extra safe, consider creating a backup before upgrading

# Upgrading
Refer to the Version 2.1 release for upgrade instructions, as they are practically identical in this release. Especially, make sure to run the `./gradlew upgrade` task after pulling in the newest changes.

# Features
- 7.0RC3 Support. [Download Page](https://jazz.net/downloads/workflow-management)
- Automated creation of p2 repositories, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/5.6-p2create)
- Automated preparation of new sdk relases, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/6.1-prepare)
- Support for customized log4j settings, enabling detailed logging in the jazz development environment, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/3.10-Log4J-Configuration)
- Support for non-ibm or otherwise custom java sdks, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/3.9-JDK-Configuration)
- Support for configuring an eclipse proxy for use with the eclipse-specific tasks, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/3.8-Eclipse-Proxy)
- Gradle Upgrade to Version 6.2. This comes with deprecation warnings of features that will not be supported in Gradle 7.0 and beyond. However, these can only be fixed gradually, as many plugins we depend on have not been brought up to speed. We will only migrate to Gradle 7+ once all of these regressions have been fixed.

# Bug Fixes
- Fixed a bug where the p2use task would create invalid repository ids on Windows.
- Fixed a bug where the p2use task would fail if no previous settings file could be found.
- Fixed a bug where running the info task would fail if bootstrap had not been run yet.
- Fixed a bug where p2 repository creation would fail for SDK Versions later than 6.0.6.

As always, a big shout-out to @MartinBenninger for helping me find bugs, bouncing off new features and helping with a lot of the testing involved.

### CODE REVIEW

**Comment by SBI-** [comment]
This release will also make https://github.com/jazz-community/jazz-p2-repository-converter redundant, as this functionality is now available from within the jazz development environment. I suggest archiving that project for reference purposes, but anybody wishing to create p2 repositories and working with them should use the functionality now provided in this project.

**Comment by MartinBenninger** [comment]
@SBI- Thank you so much for this new release and the detailed documentation! 🚀 📖 

These awesome new features will be very useful. I'm away for the rest of the week, but I'll test them all next week when I get back.

**Comment by SBI-** [comment]
I have added previously missing documentation:

- Support for customized log4j settings, enabling detailed logging in the jazz development environment, documented [in the wiki)(https://github.com/jazz-community/jazz-debug-environment/wiki/3.10-Log4J-Configuration)
- Support for non-ibm or otherwise custom java sdks, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/3.9-JDK-Configuration)
- Support for configuring an eclipse proxy for use with the eclipse-specific tasks, documented [in the wiki](https://github.com/jazz-community/jazz-debug-environment/wiki/3.8-Eclipse-Proxy)

I'm sure that documentation could me more thorough, but the default settings should be enough for most users, and all config files come with enough documentation to at least make general sense. I would be super happy for anybody using the new features to enhance the documentation where appropriate.

**Comment by SBI-** [comment]
I have reassigned @MartinBenninger to complete this pull request, as it is very likely that I will not have access to the internet due to traveling. If there are no major issues, you can use the text in the pull request to prepare a new release for version 2.3 :+1:

**Comment by SBI-** [comment]
Reassigned. Traveling seems to be off the menu and I'm in quarantine  :grin:

**Comment by MartinBenninger** [comment]
> Reassigned. Traveling seems to be off the menu and I'm in quarantine 😁

Sorry to hear that. The world is getting a bit crazy right now. I hope that you're healthy and out of quarantine soon.

**Pull request merged**
